import { Booking, CheckInLog, Court, Player } from '../types';

export function getTodayDateString(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export const INITIAL_COURTS: Court[] = [
  {
    id: 'court-1',
    name: 'คอร์ท 1 (Court 1)',
    type: 'standard_rubber',
    pricePerHour: 200,
    status: 'in_play',
    currentBookingId: 'bk-101',
    lightingStatus: 'on',
  },
  {
    id: 'court-2',
    name: 'คอร์ท 2 (Court 2)',
    type: 'standard_rubber',
    pricePerHour: 200,
    status: 'booked',
    currentBookingId: 'bk-102',
    lightingStatus: 'off',
  },
  {
    id: 'court-3',
    name: 'คอร์ท 3 (Court 3)',
    type: 'standard_rubber',
    pricePerHour: 200,
    status: 'available',
    lightingStatus: 'off',
  },
  {
    id: 'court-4',
    name: 'คอร์ท 4 (Court 4)',
    type: 'parquet_wood',
    pricePerHour: 240,
    status: 'in_play',
    currentBookingId: 'bk-103',
    lightingStatus: 'on',
  },
  {
    id: 'court-5',
    name: 'คอร์ท 5 (Court 5)',
    type: 'parquet_wood',
    pricePerHour: 240,
    status: 'available',
    lightingStatus: 'off',
  },
  {
    id: 'court-6',
    name: 'คอร์ท 6 (VIP Air-Con)',
    type: 'vip_aircon',
    pricePerHour: 350,
    status: 'booked',
    currentBookingId: 'bk-104',
    lightingStatus: 'off',
  },
];

export const INITIAL_PLAYERS: Player[] = [
  {
    id: 'pl-1',
    code: 'PL-8801',
    name: 'คุณธนกฤต กิตติศักดิ์ (เบนซ์)',
    phone: '081-456-7890',
    email: 'thanakrit.b@gmail.com',
    lineId: 'benz_smash',
    skillLevel: 'advanced',
    memberType: 'member',
    totalVisits: 28,
    totalHours: 56,
    totalSpent: 11200,
    createdAt: '2026-01-15',
    notes: 'ชอบเล่นคอร์ท 1-2 สั่งลูกขนไก่ RSL Silver ประจำ',
  },
  {
    id: 'pl-2',
    code: 'PL-8802',
    name: 'คุณกัญญาภัค วรพงษ์ (พลอย)',
    phone: '089-223-4567',
    email: 'ploy.k@hotmail.com',
    lineId: 'ploy_badminton',
    skillLevel: 'intermediate',
    memberType: 'member',
    totalVisits: 15,
    totalHours: 30,
    totalSpent: 6400,
    createdAt: '2026-03-10',
    notes: 'มาเล่นกับแก๊งออฟฟิศวันศุกร์และเสาร์-อาทิตย์',
  },
  {
    id: 'pl-3',
    code: 'PL-8803',
    name: 'คุณพีรพัฒน์ ศรีสุข (อาร์ม)',
    phone: '095-789-1234',
    email: 'peerapat.arm@gmail.com',
    lineId: 'arm_ace',
    skillLevel: 'intermediate',
    memberType: 'guest',
    totalVisits: 6,
    totalHours: 12,
    totalSpent: 2640,
    createdAt: '2026-07-02',
    notes: 'เช่าไม้แบด Yonex 2 อันทุกครั้ง',
  },
  {
    id: 'pl-4',
    code: 'PL-8804',
    name: 'คุณณัฐณิชา เจริญพร (แนน)',
    phone: '082-998-3412',
    email: 'natnicha.nan@gmail.com',
    lineId: 'nan_smash88',
    skillLevel: 'beginner',
    memberType: 'guest',
    totalVisits: 4,
    totalHours: 8,
    totalSpent: 2100,
    createdAt: '2026-08-14',
    notes: 'มือใหม่ซ้อมเดี่ยวช่วงค่ำ',
  },
  {
    id: 'pl-5',
    code: 'PL-8805',
    name: 'ทีมชมรมแบดมินตันศิษย์เก่า (พี่โต้ง)',
    phone: '086-334-9001',
    email: 'tong.alumni@yahoo.com',
    lineId: 'tong_badminton',
    skillLevel: 'advanced',
    memberType: 'member',
    totalVisits: 42,
    totalHours: 98,
    totalSpent: 24500,
    createdAt: '2025-11-20',
    notes: 'จองประจำสัปดาห์ละ 2 วัน คอร์ท VIP หรือปาร์เก้',
  },
];

export function generateInitialBookings(today: string): Booking[] {
  return [
    // Completed morning session 1
    {
      id: 'bk-099',
      bookingCode: 'BDM-260920-001',
      courtId: 'court-1',
      courtName: 'คอร์ท 1 (Court 1)',
      playerId: 'pl-2',
      playerName: 'คุณกัญญาภัค วรพงษ์ (พลอย)',
      playerPhone: '089-223-4567',
      date: today,
      startTime: '09:00',
      endTime: '11:00',
      hours: 2,
      courtFee: 400,
      racketRentalQty: 0,
      shuttlecockQty: 1,
      equipmentFee: 80,
      totalAmount: 480,
      paymentStatus: 'paid',
      checkInStatus: 'completed',
      checkedInAt: '08:55',
      checkedOutAt: '11:02',
      notes: 'เช็คอินตรงเวลา ชำระผ่าน QR PromptPay',
      createdAt: `${today} 08:30`,
    },
    // Completed morning session 2
    {
      id: 'bk-100',
      bookingCode: 'BDM-260920-002',
      courtId: 'court-3',
      courtName: 'คอร์ท 3 (Court 3)',
      playerId: 'pl-3',
      playerName: 'คุณพีรพัฒน์ ศรีสุข (อาร์ม)',
      playerPhone: '095-789-1234',
      date: today,
      startTime: '10:00',
      endTime: '12:00',
      hours: 2,
      courtFee: 400,
      racketRentalQty: 2,
      shuttlecockQty: 2,
      equipmentFee: 260,
      totalAmount: 660,
      paymentStatus: 'paid',
      checkInStatus: 'completed',
      checkedInAt: '09:58',
      checkedOutAt: '12:05',
      notes: 'เช่าไม้ 2 อัน ลูกแบด 2 หลอด',
      createdAt: `${today} 09:15`,
    },
    // Currently In Play: Court 1
    {
      id: 'bk-101',
      bookingCode: 'BDM-260920-003',
      courtId: 'court-1',
      courtName: 'คอร์ท 1 (Court 1)',
      playerId: 'pl-1',
      playerName: 'คุณธนกฤต กิตติศักดิ์ (เบนซ์)',
      playerPhone: '081-456-7890',
      date: today,
      startTime: '14:00',
      endTime: '16:00',
      hours: 2,
      courtFee: 400,
      racketRentalQty: 0,
      shuttlecockQty: 1,
      equipmentFee: 85,
      totalAmount: 485,
      paymentStatus: 'paid',
      checkInStatus: 'checked_in',
      checkedInAt: '13:58',
      notes: 'สแกน QR Code เช็คอินสำเร็จ - กำลังลงเล่น',
      createdAt: `${today} 11:00`,
    },
    // Booked upcoming: Court 2
    {
      id: 'bk-102',
      bookingCode: 'BDM-260920-004',
      courtId: 'court-2',
      courtName: 'คอร์ท 2 (Court 2)',
      playerId: 'pl-4',
      playerName: 'คุณณัฐณิชา เจริญพร (แนน)',
      playerPhone: '082-998-3412',
      date: today,
      startTime: '16:00',
      endTime: '18:00',
      hours: 2,
      courtFee: 400,
      racketRentalQty: 1,
      shuttlecockQty: 1,
      equipmentFee: 135,
      totalAmount: 535,
      paymentStatus: 'paid',
      checkInStatus: 'not_checked_in',
      notes: 'รอลูกค้ามาถึงและสแกนเช็คอินที่หน้าสนาม',
      createdAt: `${today} 12:30`,
    },
    // Currently In Play: Court 4
    {
      id: 'bk-103',
      bookingCode: 'BDM-260920-005',
      courtId: 'court-4',
      courtName: 'คอร์ท 4 (Court 4)',
      playerId: 'pl-5',
      playerName: 'ทีมชมรมแบดมินตันศิษย์เก่า (พี่โต้ง)',
      playerPhone: '086-334-9001',
      date: today,
      startTime: '14:30',
      endTime: '17:30',
      hours: 3,
      courtFee: 720,
      racketRentalQty: 0,
      shuttlecockQty: 3,
      equipmentFee: 255,
      totalAmount: 975,
      paymentStatus: 'paid',
      checkInStatus: 'checked_in',
      checkedInAt: '14:26',
      notes: 'เปิดไฟสปอร์ตไลท์เต็มระบบ',
      createdAt: `${today} 10:00`,
    },
    // Booked upcoming: Court 6 VIP
    {
      id: 'bk-104',
      bookingCode: 'BDM-260920-006',
      courtId: 'court-6',
      courtName: 'คอร์ท 6 (VIP Air-Con)',
      playerId: 'pl-1',
      playerName: 'คุณธนกฤต กิตติศักดิ์ (เบนซ์)',
      playerPhone: '081-456-7890',
      date: today,
      startTime: '18:00',
      endTime: '20:00',
      hours: 2,
      courtFee: 700,
      racketRentalQty: 0,
      shuttlecockQty: 2,
      equipmentFee: 170,
      totalAmount: 870,
      paymentStatus: 'pending',
      checkInStatus: 'not_checked_in',
      notes: 'จองล่วงหน้าคอร์ท VIP แอร์ มีเครื่องดื่ม',
      createdAt: `${today} 13:00`,
    },
  ];
}

export function generateInitialCheckIns(today: string): CheckInLog[] {
  return [
    {
      id: 'chk-1',
      bookingId: 'bk-099',
      bookingCode: 'BDM-260920-001',
      courtId: 'court-1',
      courtName: 'คอร์ท 1 (Court 1)',
      playerId: 'pl-2',
      playerName: 'คุณกัญญาภัค วรพงษ์ (พลอย)',
      playerPhone: '089-223-4567',
      date: today,
      checkInTime: '08:55:12',
      checkOutTime: '11:02:40',
      sessionStartTime: '09:00',
      sessionEndTime: '11:00',
      status: 'completed',
      method: 'qr_scan',
      notes: 'สแกน QR ผ่านโทรศัพท์มือถือ',
    },
    {
      id: 'chk-2',
      bookingId: 'bk-100',
      bookingCode: 'BDM-260920-002',
      courtId: 'court-3',
      courtName: 'คอร์ท 3 (Court 3)',
      playerId: 'pl-3',
      playerName: 'คุณพีรพัฒน์ ศรีสุข (อาร์ม)',
      playerPhone: '095-789-1234',
      date: today,
      checkInTime: '09:58:30',
      checkOutTime: '12:05:15',
      sessionStartTime: '10:00',
      sessionEndTime: '12:00',
      status: 'completed',
      method: 'qr_scan',
      notes: 'สแกนบัตรสมาชิกล่วงหน้า 2 นาที',
    },
    {
      id: 'chk-3',
      bookingId: 'bk-101',
      bookingCode: 'BDM-260920-003',
      courtId: 'court-1',
      courtName: 'คอร์ท 1 (Court 1)',
      playerId: 'pl-1',
      playerName: 'คุณธนกฤต กิตติศักดิ์ (เบนซ์)',
      playerPhone: '081-456-7890',
      date: today,
      checkInTime: '13:58:45',
      sessionStartTime: '14:00',
      sessionEndTime: '16:00',
      status: 'active',
      method: 'qr_scan',
      notes: 'กำลังลงซ้อมเดี่ยว',
    },
    {
      id: 'chk-4',
      bookingId: 'bk-103',
      bookingCode: 'BDM-260920-005',
      courtId: 'court-4',
      courtName: 'คอร์ท 4 (Court 4)',
      playerId: 'pl-5',
      playerName: 'ทีมชมรมแบดมินตันศิษย์เก่า (พี่โต้ง)',
      playerPhone: '086-334-9001',
      date: today,
      checkInTime: '14:26:10',
      sessionStartTime: '14:30',
      sessionEndTime: '17:30',
      status: 'active',
      method: 'qr_scan',
      notes: 'สมาชิก 4 คน สแกนพร้อมกัน',
    },
  ];
}
